/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ux_ui;

import dao.CongTacDAO;
import entity.CongTac;
import entity.Luong;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import library.MsgBox;

/**
 *
 * @author TAN LOC
 */
public class JDialogCongTac extends javax.swing.JDialog {
    
    CongTacDAO dao = new CongTacDAO();
    int row = -1;

    /**
     * Creates new form JDialogCongTac
     */
    public JDialogCongTac(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabs = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblquanlicongtac = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        txtTimKiem = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lblCongTac = new javax.swing.JLabel();
        txtCongTac = new javax.swing.JTextField();
        tblNgayCoHieuLuat = new javax.swing.JLabel();
        txtNgayCoHieuLuat = new javax.swing.JTextField();
        lblNhiemVuCU = new javax.swing.JLabel();
        txtNhiemVuCu = new javax.swing.JTextField();
        lblSoQuyetDinh = new javax.swing.JLabel();
        txtSoQuyetDinh = new javax.swing.JTextField();
        btnthem = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        btnmoi = new javax.swing.JButton();
        btnlast = new javax.swing.JButton();
        btnnext = new javax.swing.JButton();
        btnpev = new javax.swing.JButton();
        btnfirst = new javax.swing.JButton();
        txtNhiemVuMoi = new javax.swing.JTextField();
        lblNhiemVuMoi = new javax.swing.JLabel();
        txtMaNhanVien = new javax.swing.JTextField();
        lblMaNhanVien = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblquanlicongtac.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã Công Tác", "Số Quyết Định", "Ngày Có Hiệu Lực", "Nhiệm Vụ Cũ", "Nhiệm Vụ Mới", "Mã Nhân Viên"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblquanlicongtac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblquanlicongtacMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblquanlicongtac);

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Tìm Kiếm");

        txtTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(29, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(37, 37, 37))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        tabs.addTab("Công Tác", jPanel1);

        lblCongTac.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCongTac.setText("Mã Công Tác");

        txtCongTac.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        tblNgayCoHieuLuat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblNgayCoHieuLuat.setText("Ngày Có Hiệu Luật");

        txtNgayCoHieuLuat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblNhiemVuCU.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNhiemVuCU.setText("Nhiệm Vụ Cũ");

        txtNhiemVuCu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblSoQuyetDinh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSoQuyetDinh.setText("Số Quyết Định");

        txtSoQuyetDinh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnthem.setText("Thêm");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        btnsua.setText("Sửa");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        btnxoa.setText("Xóa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        btnmoi.setText("Mới");
        btnmoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmoiActionPerformed(evt);
            }
        });

        btnlast.setText(">|");
        btnlast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlastActionPerformed(evt);
            }
        });

        btnnext.setText(">>");
        btnnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnextActionPerformed(evt);
            }
        });

        btnpev.setText("<<");
        btnpev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpevActionPerformed(evt);
            }
        });

        btnfirst.setText("|<");
        btnfirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfirstActionPerformed(evt);
            }
        });

        txtNhiemVuMoi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblNhiemVuMoi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNhiemVuMoi.setText("Nhiêm Vụ Mới");

        txtMaNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblMaNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMaNhanVien.setText("Mã Nhân Viên");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnthem, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnsua, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnxoa, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnmoi, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btnfirst, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnpev, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnnext, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnlast, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtNhiemVuMoi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                                .addComponent(txtCongTac, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNgayCoHieuLuat, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tblNgayCoHieuLuat, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblCongTac, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(lblNhiemVuMoi))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNhiemVuCu, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                            .addComponent(lblSoQuyetDinh)
                            .addComponent(lblNhiemVuCU)
                            .addComponent(txtSoQuyetDinh)
                            .addComponent(lblMaNhanVien)
                            .addComponent(txtMaNhanVien))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblCongTac)
                        .addGap(18, 18, 18)
                        .addComponent(txtCongTac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblSoQuyetDinh)
                        .addGap(18, 18, 18)
                        .addComponent(txtSoQuyetDinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tblNgayCoHieuLuat)
                        .addGap(18, 18, 18)
                        .addComponent(txtNgayCoHieuLuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblNhiemVuCU)
                        .addGap(18, 18, 18)
                        .addComponent(txtNhiemVuCu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblNhiemVuMoi)
                        .addGap(18, 18, 18)
                        .addComponent(txtNhiemVuMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblMaNhanVien)
                        .addGap(18, 18, 18)
                        .addComponent(txtMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnfirst)
                        .addComponent(btnpev)
                        .addComponent(btnnext)
                        .addComponent(btnlast))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnthem)
                        .addComponent(btnsua)
                        .addComponent(btnxoa)
                        .addComponent(btnmoi)))
                .addGap(38, 38, 38))
        );

        tabs.addTab("Chi Tiết Công Tác", jPanel2);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Quản lí công tác");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(332, 332, 332)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 806, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabs)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblquanlicongtacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblquanlicongtacMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            row = tblquanlicongtac.getSelectedRow();
            edit();
        }
    }//GEN-LAST:event_tblquanlicongtacMouseClicked

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        // TODO add your handling code here:
        insert();
    }//GEN-LAST:event_btnthemActionPerformed

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        // TODO add your handling code here:
        update();
    }//GEN-LAST:event_btnsuaActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        delete();
    }//GEN-LAST:event_btnxoaActionPerformed

    private void btnmoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmoiActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnmoiActionPerformed

    private void btnlastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlastActionPerformed
        // TODO add your handling code here:
        last();
    }//GEN-LAST:event_btnlastActionPerformed

    private void btnnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnextActionPerformed
        // TODO add your handling code here:
        next();
    }//GEN-LAST:event_btnnextActionPerformed

    private void btnpevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpevActionPerformed
        // TODO add your handling code here:
        prev();
    }//GEN-LAST:event_btnpevActionPerformed

    private void btnfirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfirstActionPerformed
        // TODO add your handling code here:
        first();
    }//GEN-LAST:event_btnfirstActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogCongTac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogCongTac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogCongTac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogCongTac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogCongTac dialog = new JDialogCongTac(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnfirst;
    private javax.swing.JButton btnlast;
    private javax.swing.JButton btnmoi;
    private javax.swing.JButton btnnext;
    private javax.swing.JButton btnpev;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btnxoa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCongTac;
    private javax.swing.JLabel lblMaNhanVien;
    private javax.swing.JLabel lblNhiemVuCU;
    private javax.swing.JLabel lblNhiemVuMoi;
    private javax.swing.JLabel lblSoQuyetDinh;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JLabel tblNgayCoHieuLuat;
    private javax.swing.JTable tblquanlicongtac;
    private javax.swing.JTextField txtCongTac;
    private javax.swing.JTextField txtMaNhanVien;
    private javax.swing.JTextField txtNgayCoHieuLuat;
    private javax.swing.JTextField txtNhiemVuCu;
    private javax.swing.JTextField txtNhiemVuMoi;
    private javax.swing.JTextField txtSoQuyetDinh;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables

    void init() {
        filltable();
    }
    
    void filltable() {
        DefaultTableModel model = (DefaultTableModel) tblquanlicongtac.getModel();
        model.setRowCount(0);
        
        try {
            ArrayList<CongTac> list = dao.select();
            for (CongTac congTac : list) {
                Object[] row = {
                    congTac.getMaCT(),
                    congTac.getSoQuyetDinh(),
                    congTac.getNgayCoHieuLuc(),
                    congTac.getNhiemVuCu(),
                    congTac.getNhiemVuMoi(),
                    congTac.getMaNV()
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    void edit() {
        String macongtac = (String) tblquanlicongtac.getValueAt(row, 0);
        try {
            CongTac congtac = dao.selectByMaCT(macongtac);
            this.setfrom(congtac);
            tabs.setSelectedIndex(1);
            this.updateStatus();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    void setfrom(CongTac congTac) {
        txtCongTac.setText(String.valueOf(congTac.getMaCT()));
        txtSoQuyetDinh.setText(String.valueOf(congTac.getSoQuyetDinh()));
        txtNgayCoHieuLuat.setText(String.valueOf(congTac.getNgayCoHieuLuc()));
        txtNhiemVuCu.setText(String.valueOf(congTac.getNhiemVuCu()));
        txtNhiemVuMoi.setText(String.valueOf(congTac.getNhiemVuMoi()));
        txtMaNhanVien.setText(String.valueOf(congTac.getMaNV()));        
        this.updateStatus();
    }
    
    boolean check() {
        String thongbao = "";
        if (txtCongTac.getText().trim().isEmpty()) {
            thongbao += "Vui lòng nhập mã công tác \n";
        }
        if (txtSoQuyetDinh.getText().trim().isEmpty()) {
            thongbao += "Vui lòng nhập số quyết định \n";
        }
        if (txtNgayCoHieuLuat.getText().trim().isEmpty()) {
            thongbao += "Vui lòng nhập ngày có hiệu luật \n";
        }
        if (txtNhiemVuCu.getText().trim().isEmpty()) {
            thongbao += "Vui lòng nhập nhiệm vụ cũ \n";
        }
        if (txtNhiemVuMoi.getText().trim().isEmpty()) {
            thongbao += "Vui lòng nhập nhiệm vụ mới\n";
        }
        if (txtMaNhanVien.getText().trim().isEmpty()) {
            thongbao += "Vui lòng nhập mã nhân viên \n";
        }
        if (thongbao.length() > 0) {
            MsgBox.alert(this, thongbao);
            return false;
        }
        return true;
    }
    
    CongTac getfrom() {
        CongTac congtac = new CongTac();
        congtac.setMaCT(txtCongTac.getText());
        congtac.setSoQuyetDinh(Integer.valueOf(txtSoQuyetDinh.getText()));
        congtac.setNgayCoHieuLuc(congtac.getNgayCoHieuLuc());
        congtac.setNhiemVuCu(txtNhiemVuCu.getText());
        congtac.setNhiemVuMoi(txtNhiemVuMoi.getText());
        congtac.setMaNV(txtMaNhanVien.getText());
        return congtac;
    }
    
    void insert() {
        if (check()) {
            String mct = txtCongTac.getText();
            try {
                CongTac ct = dao.selectByMaCT(mct);
                if (ct!= null) {
                    MsgBox.alert(this, "Mã công tác này đã tồn tại");
                    return;
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
            
            CongTac congtac = getfrom();
            
            try {
                dao.insert(congtac);
                filltable();
                MsgBox.alert(this, "Thêm mới thành công");
            } catch (Exception e) {
                e.printStackTrace();
                MsgBox.alert(this, "Thêm mới thất bại");
            }
        }
    }
    
    void update() {
        if (check()) {
            CongTac ct = getfrom();
            try {
                dao.update(ct);
                filltable();
                MsgBox.alert(this, "Update thành công");
            } catch (Exception e) {
                e.printStackTrace();
                MsgBox.alert(this, "Update thất bại");
            }
        }
    }
    
    void delete() {
        if (MsgBox.confirm(this, "Bạn có chắc muốn xóa không")) {
            try {
                CongTac ct = getfrom();
                dao.delete(ct);
                this.filltable();
                this.clear();
                MsgBox.alert(this, "Xóa thành công!");
            } catch (Exception e) {
                e.printStackTrace();
                MsgBox.alert(this, "Xóa thất bại!");
            }
        }
        
    }
    
    void clear() {
        CongTac ct = new CongTac();
        this.setfrom(ct);
        row = -1;
    }
    
    void updateStatus() {
        boolean edit = (this.row >= 0);
        boolean first = (this.row == 0);
        boolean last = (this.row == tblquanlicongtac.getRowCount() - 1);
        btnthem.setEnabled(!edit);
        btnsua.setEnabled(edit);
        btnxoa.setEnabled(edit);
        btnfirst.setEnabled(edit && !first);
        btnpev.setEnabled(edit && !first);
        btnnext.setEnabled(edit && !last);
        btnlast.setEnabled(edit && !last);
    }
    
    void first() {
        this.row = 0;
        this.edit();
    }
    
    void last() {
        this.row = tblquanlicongtac.getRowCount() - 1;
        this.edit();
    }
    
    void prev() {
        if (row > 0) {
            this.row--;
            this.edit();
        }
    }
    
    void next() {
        if (this.row < tblquanlicongtac.getRowCount() - 1) {
            this.row++;
            this.edit();
        }
    }
}
